[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/assets/index-Ce6zReou.js"
  to = "/assets/index-Ce6zReou.js"
  status = 200
  force = true
  headers = { Content-Type = "application/javascript; charset=utf-8", Cache-Control = "public, max-age=31536000, immutable" }

[[redirects]]
  from = "/assets/index-ZES75bOR.css"
  to = "/assets/index-ZES75bOR.css"
  status = 200
  force = true
  headers = { Content-Type = "text/css", Cache-Control = "public, max-age=31536000, immutable" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "script-src 'self' 'unsafe-inline' 'unsafe-eval'; connect-src 'self' https://cloud.appwrite.io;"
